branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: add
          release: minor
        - breaking: true
          release: minor
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: change
          release: minor
        - type: deprecate
          release: minor
        - type: remove
          release: minor
        - type: security
          release: patch
        - type: chore
          release: patch
        - type: docs
          scope: README
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: perf
          release: patch
        - type: test
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
        - path: "./var/*"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
