services:
  postgres:
    image: postgres:16
    environment: &postgres-env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: project

      PGUSER: admin
      PGPASSWORD: hunter2
      PGDATABASE: project
      PGHOST: postgres
      PGPORT: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8
    pull_policy: always
    environment:
      VALKEY_EXTRA_FLAGS: "--save 60 1 --loglevel warning"
    volumes:
      - valkey-data:/data

  # VS Code workspace service
  workspace:
    image: ghcr.io/xe/project-template/devcontainer:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace/tygen:cached
    # entrypoint: ["/usr/bin/sleep", "infinity"]
    user: vscode
    environment:
      <<: *postgres-env
      DATABASE_URL: postgresql://admin:hunter2@postgres/project?sslmode=disable
      REDIS_URL: redis://valkey:6379/0

volumes:
  postgres-data:
  valkey-data:
